services:
  cloudflare:
    image: cloudflare/cloudflared:latest
    init: true
    restart: always
    environment:
      UUID: ${UUID}
    volumes:
      - ./tunnel:/var/cloudflared
      - ${cloudflare_DDDC}/startup:/opt/startup:ro
    entrypoint:
      - /opt/startup
    command:
      - tunnel
      - --config
      - /etc/cloudflared/config.yml
      - --post-quantum
      - run
      - ${CLOUDFLARE_DOMAIN_ID}
