services:
  cloudflare:
    build:
      context: ${cloudflare_DDDC}
      dockerfile: Dockerfile
    init: true
    restart: always
    user: root
    environment:
      UUID: ${UUID}
    volumes:
      - ./tunnel:/var/cloudflared
    entrypoint:
      - /opt/startup
    command:
      - --post-quantum
      - tunnel
      - run
      - ${CLOUDFLARE_DOMAIN_ID}
